version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rednortedb
    #ports:
      #- "3306:3306"
    volumes:
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PRIMARY_DB_URL: jdbc:mysql://mysql:3306/rednortedb
      PRIMARY_DB_USERNAME: root
      PRIMARY_DB_PASSWORD: root

      ESPERA_DB_URL: jdbc:mysql://mysql:3306/rednorte_espera
      ESPERA_DB_USERNAME: root
      ESPERA_DB_PASSWORD: root

      NOTIFICACIONES_DB_URL: jdbc:mysql://mysql:3306/rednorte_notificaciones
      NOTIFICACIONES_DB_USERNAME: root
      NOTIFICACIONES_DB_PASSWORD: root

      REASIGNACIONES_DB_URL: jdbc:mysql://mysql:3306/rednorte_reasignaciones
      REASIGNACIONES_DB_USERNAME: root
      REASIGNACIONES_DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend