# Configuración del servidor
server.port=8081
spring.application.name=ms-listas-espera

# Conexión a su propia Base de Datos separada
spring.datasource.url=jdbc:mysql://localhost:3306/listas_espera_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true