name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  frontTest-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Habilitado para acelerar futuras ejecuciones

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar los Test
        # Eliminamos --watchAll=false porque Vitest usa "run" para CI
        run: npm test

  backTest-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Dar Permisos a maven
        run: chmod +x mvnw

      - name: Ejecutar las pruebas
        # Cambiado de 'compile' a 'test' para que realmente valide el código
        run: ./mvnw test

  front-build:
    needs: frontTest-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar las dependencias
        run: npm install

      - name: Construir la aplicacion
        run: npm run build 

  back-build:
    needs: backTest-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Dar permisos a maven
        run: chmod +x mvnw

      - name: Construir la aplicación
        run: ./mvnw clean package -DskipTests