name: CI RedNorte Backend

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
    
  workflow_dispatch: # Esto añade el botón

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y ejecutar pruebas
        run: mvn clean verify --no-transfer-progress

      - name: Publicar reporte de cobertura JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar paso
        run: echo "El flujo se ha ejecutado manualmente"